name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
    branches: ["master"]

jobs:

  linux-windows-build:
    name: MSBuild Build
    if: startsWith( github.ref, 'refs/tags/v')
    runs-on: windows-2019
    timeout-minutes: 45
    steps:

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
  
    - name: Check out code
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Download Tools
      run: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile jq.exe
        Invoke-WebRequest -Uri https://github.com/moloch--/minisign/releases/download/v0.2.1/minisign.exe -OutFile minisign.exe

    - name: MSBuild
      run: |
        nuget.exe restore Backstab.sln
        msbuild.exe Backstab.sln /p:Configuration=Release /p:Platform="x64" /p:OutputPath=compiled/
        msbuild.exe Backstab.sln /p:Configuration=Release /p:Platform="x86" /p:OutputPath=compiled/
        Copy-Item -Path x64\Release\Backstab.exe -Destination compiled\backstab.exe
        Copy-Item -Path Release\Backstab.exe -Destination compiled\backstab32.exe

    - name: Build Package
      # Powershell is utter fucking trash.
      run: |
        ls
        $Version = git.exe describe --tags --abbrev=0
        $Version = "`"$Version`""
        Get-Content -Path extension.json | .\jq.exe ".version |= `"$Version`"" > ./compiled/extension.json
        cd compiled
        tar.exe -czvf ..\Backstab.tar.gz .

    - name: Sign Package
      run: |
        Write-Output "${{ secrets.MINISIGN_PRIVATE_KEY }}" > minisign.key
        $Content1 = Get-Content -Path ./compiled/extension.json
        $Bytes = [System.Text.Encoding]::UTF8.GetBytes($Content1)
        $Encoded = [System.Convert]::ToBase64String($Bytes)
        .\minisign.exe -s minisign.key -S -m Backstab.tar.gz -t "$Encoded" -x Backstab.minisig

    - name: "Publish Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          Backstab.minisig
          Backstab.tar.gz
